// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "post": {
                "description": "Аутентифицирует врача по номеру телефона и паролю",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DoctorLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное создание",
                        "schema": {
                            "$ref": "#/definitions/models.DoctorAuthResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "401": {
                        "description": "Неверные учётные данные",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/doctors/{doc_id}": {
            "get": {
                "description": "Возвращает данные врача по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "Получить врача по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID врача",
                        "name": "doc_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные врача",
                        "schema": {
                            "$ref": "#/definitions/entities.Doctor"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "404": {
                        "description": "Врач не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет информацию о враче",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "Обновить данные врача",
                "parameters": [
                    {
                        "description": "Данные для обновления",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateDoctorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Обновленный врач",
                        "schema": {
                            "$ref": "#/definitions/entities.Doctor"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "404": {
                        "description": "Врач не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.NotFoundError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/emergency/receptions": {
            "post": {
                "description": "Возвращает созданное заключение",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMP"
                ],
                "summary": "Создать заключение на скорой",
                "parameters": [
                    {
                        "description": "Данные для создания заключения",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateEmergencyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Создание заключения для пациента",
                        "schema": {
                            "$ref": "#/definitions/entities.ReceptionSMP"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/emergency/receptions/{recep_id}": {
            "put": {
                "description": "Обновляет информацию о приёvе в больнице",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMP"
                ],
                "summary": "Обновить приём в больнице",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID приёма",
                        "name": "recep_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateReceptionHospitalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.ReceptionHospital"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "401": {
                        "description": "Некорректный ID приёма",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/emergency/{doctor_id}": {
            "get": {
                "description": "Возвращает список экстренных приёмов, назначенных врачу на указанную дату, с пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMP"
                ],
                "summary": "Получить экстренные приёмы врача по дате",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID врача",
                        "name": "doctor_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата в формате YYYY-MM-DD",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список приёмов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.EmergencyCall"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/emergency/{doctor_id}/{recep_id}": {
            "get": {
                "description": "Возвращает список приёмов скорой медицинской помощи для указанного врача с пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMP"
                ],
                "summary": "Получить СМП приёмы врача по дате",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID врача",
                        "name": "doctor_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "Количество записей на страницу",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о приёме скорой помощи",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.ReceptionSMP"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "401": {
                        "description": "Некорректный ID вызова",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/emergency/{doctor_id}/{recep_id}/{smp_id}": {
            "get": {
                "description": "Возвращает информацию о приёме скорой медицинской помощи вместе со списком медицинских услуг",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMP"
                ],
                "summary": "Получить приём СМП с медуслугами по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID приёма СМП",
                        "name": "smp_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о приёме и медуслугах",
                        "schema": {
                            "$ref": "#/definitions/entities.MedService"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "401": {
                        "description": "Некорректный ID вызова",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/hospital/receptions/patients/{pat_id}": {
            "get": {
                "description": "История приемов пациента в больнице",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HospitalReception"
                ],
                "summary": "Получить список приёмов пациента по его ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пациента",
                        "name": "pat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы\n(по умолчанию 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Количество записей на странице\n(по умолчанию 0 — без ограничения)",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр в формате field.operation.value.\nПримеры:\nrecommendations.like.режим - поле с подстрокой 'режим',\ndate.eq.2025-07-10 - фильтр по дате\ndate.eq.14:00:00 - фильтр по времени",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Сортировка в формате field.direction.\nПримеры:\ndate.desc - по убыванию даты,\nid.asc - по возрастанию id",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "История приёмов списком",
                        "schema": {
                            "$ref": "#/definitions/models.ReceptionHospitalListResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "401": {
                        "description": "Некорректный ID пациента",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/hospital/receptions/{doc_id}": {
            "get": {
                "description": "История приёмов пациентов у конкретного врача в больнице. Если ` + "`" + `doctor_id` + "`" + ` = 0, возвращаются все приёмы всех врачей.\nПо умолчанию сортировка по статусу - \"Запланирован\" и дате приема.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HospitalReception"
                ],
                "summary": "Получить список приёмов врача по его ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID врача",
                        "name": "doc_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер страницы\n(по умолчанию 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Количество записей на странице\n(по умолчанию 0 — без ограничения)",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр в формате field.operation.value.\nПримеры:\nrecommendations.like.режим - поле с подстрокой 'режим',\ndate.eq.2025-07-10 - фильтр по дате\ndate.eq.14:00:00 - фильтр по времени",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Сортировка в формате field.direction.\nПримеры:\ndate.desc - по убыванию даты,\nid.asc - по возрастанию id",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "История приёмов врача списком",
                        "schema": {
                            "$ref": "#/definitions/models.ReceptionHospitalListResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "401": {
                        "description": "Некорректный ID доктора",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/hospital/receptions/{recep_id}": {
            "put": {
                "description": "Обновляет информацию о приёме в больнице по его ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HospitalReception"
                ],
                "summary": "Обновить приём в больнице",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID приёма",
                        "name": "recep_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления приёма",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateReceptionHospitalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённый приём",
                        "schema": {
                            "$ref": "#/definitions/entities.ReceptionHospital"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "401": {
                        "description": "Некорректный ID приёма",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/medcard/{pat_id}": {
            "get": {
                "description": "Возвращает полную информацию из медицинской карты пациента",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Medcard"
                ],
                "summary": "Получить медкарту пациента по его ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пациента",
                        "name": "pat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Медицинская карта пациента",
                        "schema": {
                            "$ref": "#/definitions/models.MedCardResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "401": {
                        "description": "Некорректный ID пациента",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "404": {
                        "description": "Медицинская карта не найдена",
                        "schema": {
                            "$ref": "#/definitions/handlers.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные в медицинской карте по ID пациента",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Medcard"
                ],
                "summary": "Обновить медицинскую карту пациента",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пациента",
                        "name": "pat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления мед карты",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateMedCardRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Обновлённая медицинская карта",
                        "schema": {
                            "$ref": "#/definitions/models.MedCardResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "404": {
                        "description": "Медицинская карта не найдена",
                        "schema": {
                            "$ref": "#/definitions/handlers.NotFoundError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/medservices/": {
            "get": {
                "description": "Возвращает список платных услуг",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MedServices"
                ],
                "summary": "Получить все доступные платные услуги",
                "responses": {
                    "200": {
                        "description": "Медицинская карта пациента",
                        "schema": {
                            "$ref": "#/definitions/models.MedServicesListResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/patients": {
            "post": {
                "description": "Создает нового пациента с персональными и контактными данными",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Создать нового пациента",
                "parameters": [
                    {
                        "description": "Данные пациента",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreatePatientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Созданный пациент",
                        "schema": {
                            "$ref": "#/definitions/entities.Patient"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectFormatError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ValidationError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        },
        "/patients/{doc_id}": {
            "get": {
                "description": "Возвращает список всех пациентов, привязанных к указанному врачу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Получить всех пациентов по ID врача",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID врача",
                        "name": "doc_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список пациентов",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handlers.ResultResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entities.Patient"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Некорректный ID врача",
                        "schema": {
                            "$ref": "#/definitions/handlers.IncorrectDataError"
                        }
                    },
                    "404": {
                        "description": "Врач не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.InternalServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Allergy": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "Пенициллин"
                },
                "patient": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Patient"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.ContactInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.Doctor": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "emergency_calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.EmergencyCall"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "login": {
                    "type": "string",
                    "example": "doctor_ivanov"
                },
                "receptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionHospital"
                    }
                },
                "specialization": {
                    "$ref": "#/definitions/entities.Specialization"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.EmergencyCall": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "+79991234567"
                },
                "created_at": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string",
                    "example": "+79991234567"
                },
                "priority": {
                    "type": "integer",
                    "example": 1
                },
                "receptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionSMP"
                    }
                },
                "type": {
                    "type": "boolean",
                    "example": true
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.MedService": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "EKG"
                },
                "price": {
                    "type": "integer",
                    "example": 100
                },
                "receptionSMP": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionSMP"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.Patient": {
            "type": "object",
            "properties": {
                "allergy": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Allergy"
                    }
                },
                "birth_date": {
                    "type": "string",
                    "example": "1980-05-15T00:00:00Z"
                },
                "contact_info": {
                    "$ref": "#/definitions/entities.ContactInfo"
                },
                "created_at": {
                    "type": "string"
                },
                "emergency_receptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionSMP"
                    }
                },
                "full_name": {
                    "type": "string",
                    "example": "Смирнов Алексей Петрович"
                },
                "id": {
                    "type": "integer"
                },
                "is_male": {
                    "type": "boolean",
                    "example": true
                },
                "on_treatment": {
                    "type": "boolean",
                    "example": false
                },
                "personal_info": {
                    "$ref": "#/definitions/entities.PersonalInfo"
                },
                "receptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionHospital"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.PersonalInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "oms": {
                    "type": "string",
                    "example": "1234567890123456"
                },
                "passport_series": {
                    "type": "string",
                    "example": "4510 123456"
                },
                "patient_id": {
                    "type": "integer",
                    "example": 1
                },
                "snils": {
                    "type": "string",
                    "example": "123-456-789 00"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.ReceptionHospital": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Москва, ул. Ленина, д. 15"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string",
                    "example": "2023-10-15T14:30:00Z"
                },
                "diagnosis": {
                    "type": "string",
                    "example": "ОРВИ"
                },
                "doctor_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer"
                },
                "patient_id": {
                    "type": "integer",
                    "example": 1
                },
                "recommendations": {
                    "type": "string",
                    "example": "Постельный режим"
                },
                "specialization_data": {
                    "description": "Специализированные данные",
                    "type": "object"
                },
                "specialization_data_decoded": {},
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entities.ReceptionStatus"
                        }
                    ],
                    "example": "scheduled"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.ReceptionSMP": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "diagnosis": {
                    "type": "string",
                    "example": "ОРВИ"
                },
                "doctor_id": {
                    "type": "integer",
                    "example": 1
                },
                "emergency_call_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer"
                },
                "med_services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.MedService"
                    }
                },
                "patient_id": {
                    "type": "integer",
                    "example": 1
                },
                "recommendations": {
                    "type": "string",
                    "example": "Постельный режим"
                },
                "specialization_data": {
                    "description": "Специализированные данные",
                    "type": "object"
                },
                "specialization_data_decoded": {},
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.ReceptionStatus": {
            "type": "string",
            "enum": [
                "scheduled",
                "completed",
                "cancelled",
                "no_show"
            ],
            "x-enum-varnames": [
                "StatusScheduled",
                "StatusCompleted",
                "StatusCancelled",
                "StatusNoShow"
            ]
        },
        "entities.Specialization": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string",
                    "example": "Терапевт"
                }
            }
        },
        "handlers.IncorrectDataError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 401
                        },
                        "message": {
                            "type": "string",
                            "example": "Некорректные данные"
                        }
                    }
                },
                "status": {
                    "description": "error",
                    "type": "string",
                    "example": "IncorrectDataError"
                }
            }
        },
        "handlers.IncorrectFormatError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 400
                        },
                        "message": {
                            "type": "string",
                            "example": "Неверный формат запроса"
                        }
                    }
                },
                "status": {
                    "description": "error",
                    "type": "string",
                    "example": "IncorrectFormatError"
                }
            }
        },
        "handlers.InternalServerError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 500
                        },
                        "message": {
                            "type": "string",
                            "example": "Внутренняя ошибка сервера"
                        }
                    }
                },
                "status": {
                    "description": "error",
                    "type": "string",
                    "example": "InternalServerError"
                }
            }
        },
        "handlers.NotFoundError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 404
                        },
                        "message": {
                            "type": "string",
                            "example": "Данные не найдены"
                        }
                    }
                },
                "status": {
                    "description": "error",
                    "type": "string",
                    "example": "NotFoundError"
                }
            }
        },
        "handlers.ResultResponse": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "description": "[AVALIABLE]: object, array of objects, empty"
                        },
                        "message": {
                            "type": "string",
                            "example": "Success operation"
                        },
                        "type": {
                            "description": "[AVALIABLE]: object, array, empty",
                            "type": "string",
                            "example": "object"
                        }
                    }
                },
                "status": {
                    "description": "ok",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handlers.ValidationError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 422
                        },
                        "message": {
                            "type": "string",
                            "example": "Ошибка валидации"
                        }
                    }
                },
                "status": {
                    "description": "error",
                    "type": "string",
                    "example": "ValidationError"
                }
            }
        },
        "models.AllergyResponse": {
            "description": "Ответ с названием аллергии",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Только название аллергии",
                    "type": "string",
                    "example": "Пыльца"
                }
            }
        },
        "models.ContactInfoData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "г. Москва, ул. Ленина, д. 10"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "phone": {
                    "type": "string",
                    "example": "+79991234567"
                }
            }
        },
        "models.ContactInfoResponse": {
            "description": "Контактная информация пациента",
            "type": "object",
            "properties": {
                "address": {
                    "description": "Физический адрес",
                    "type": "string",
                    "example": "Москва, ул. Пушкина, д. 10"
                },
                "email": {
                    "description": "Электронная почта",
                    "type": "string",
                    "example": "patient@example.com"
                },
                "phone": {
                    "description": "Номер телефона",
                    "type": "string",
                    "example": "+79991234567"
                }
            }
        },
        "models.CreateEmergencyRequest": {
            "type": "object",
            "required": [
                "doctor_id",
                "emergency_call_id"
            ],
            "properties": {
                "doctor_id": {
                    "type": "integer",
                    "example": 1
                },
                "emergency_call_id": {
                    "type": "integer",
                    "example": 1
                },
                "patient": {
                    "$ref": "#/definitions/models.PatientData"
                },
                "patient_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.CreatePatientRequest": {
            "description": "Данные для создания нового пациента",
            "type": "object",
            "properties": {
                "birth_date": {
                    "description": "Дата рождения",
                    "type": "string",
                    "example": "1980-05-15"
                },
                "full_name": {
                    "description": "ФИО пациента",
                    "type": "string",
                    "example": "Смирнов Алексей Петрович"
                },
                "is_male": {
                    "description": "Пол (true - мужской)",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.DoctorAuthResponse": {
            "description": "Ответ с данными авторизованного врача",
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID врача",
                    "type": "integer",
                    "example": 1
                },
                "token": {
                    "description": "JWT токен",
                    "type": "string",
                    "example": "eyJhbGciOi..."
                }
            }
        },
        "models.DoctorInfoResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Полное имя врача",
                    "type": "string",
                    "example": "Иванов Иван Иванович"
                },
                "specialization": {
                    "$ref": "#/definitions/entities.Specialization"
                }
            }
        },
        "models.DoctorLoginRequest": {
            "description": "Запрос для входа врача в систему",
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Пароль",
                    "type": "string",
                    "example": "123"
                },
                "username": {
                    "description": "Логин (телефон)",
                    "type": "string",
                    "example": "doctor_ivanov"
                }
            }
        },
        "models.MedCardResponse": {
            "description": "Содержит всю медицинскую информацию о пациенте",
            "type": "object",
            "properties": {
                "allergy": {
                    "description": "Список аллергий",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AllergyResponse"
                    }
                },
                "contact_info": {
                    "description": "Контактные данные",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ContactInfoResponse"
                        }
                    ]
                },
                "patient": {
                    "description": "Основные данные пациента",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ShortPatientResponse"
                        }
                    ]
                },
                "personal_info": {
                    "description": "Персональная информация",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PersonalInfoResponse"
                        }
                    ]
                }
            }
        },
        "models.MedServicesListResponse": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MedServicesResponse"
                    }
                },
                "totalHits": {
                    "type": "integer"
                }
            }
        },
        "models.MedServicesResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "EKG"
                },
                "price": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "models.PatientData": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "1980-05-15T00:00:00Z"
                },
                "contact_info": {
                    "description": "Опциональные контактные данные",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ContactInfoData"
                        }
                    ]
                },
                "full_name": {
                    "type": "string",
                    "example": "Иванов Иван Иванович"
                },
                "is_male": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.PersonalInfoResponse": {
            "description": "Документы и идентификационные данные пациента",
            "type": "object",
            "properties": {
                "oms": {
                    "description": "Номер полиса ОМС",
                    "type": "string",
                    "example": "1234567890123456"
                },
                "passport_series": {
                    "description": "Серия и номер паспорта",
                    "type": "string",
                    "example": "4510 123456"
                },
                "snils": {
                    "description": "Номер СНИЛС",
                    "type": "string",
                    "example": "123-456-789 00"
                }
            }
        },
        "models.ReceptionHospitalListResponse": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "hits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ReceptionHospitalResponse"
                    }
                },
                "hitsPerPage": {
                    "type": "integer"
                },
                "totalHits": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "models.ReceptionHospitalResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2023-10-15T14:30:00Z"
                },
                "diagnosis": {
                    "type": "string",
                    "example": "ОРВИ"
                },
                "doctor": {
                    "$ref": "#/definitions/models.DoctorInfoResponse"
                },
                "patient": {
                    "$ref": "#/definitions/models.ShortPatientResponse"
                },
                "recommendations": {
                    "type": "string",
                    "example": "Постельный режим"
                }
            }
        },
        "models.ShortPatientResponse": {
            "description": "Сокращенные данные пациента",
            "type": "object",
            "properties": {
                "birth_date": {
                    "description": "Дата рождения",
                    "type": "string",
                    "example": "1980-05-15T00:00:00Z"
                },
                "full_name": {
                    "description": "ФИО пациента",
                    "type": "string",
                    "example": "Смирнов Алексей Петрович"
                },
                "id": {
                    "description": "ID пациента",
                    "type": "integer"
                },
                "is_male": {
                    "description": "Пол (true - мужской)",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.UpdateDoctorRequest": {
            "description": "Используется для изменения информации о враче",
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Иванов Иван Иванович"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "login": {
                    "type": "string",
                    "example": "+79123456789"
                },
                "specialization_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.UpdateMedCardRequest": {
            "description": "Содержит всю медицинскую информацию о пациенте",
            "type": "object",
            "properties": {
                "allergy": {
                    "description": "Список аллергий",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AllergyResponse"
                    }
                },
                "contact_info": {
                    "description": "Контактные данные",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ContactInfoResponse"
                        }
                    ]
                },
                "patient": {
                    "description": "Основные данные пациента",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ShortPatientResponse"
                        }
                    ]
                },
                "personal_info": {
                    "description": "Персональная информация",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PersonalInfoResponse"
                        }
                    ]
                }
            }
        },
        "models.UpdateReceptionHospitalRequest": {
            "type": "object",
            "properties": {
                "diagnosis": {
                    "type": "string",
                    "example": "Грипп"
                },
                "id": {
                    "type": "integer"
                },
                "recommendations": {
                    "type": "string",
                    "example": "Постельный режим"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entities.ReceptionStatus"
                        }
                    ],
                    "example": "scheduled"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ClinicHub API",
	Description:      "API для работы с приёмами пациентов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
