// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "post": {
                "description": "Аутентифицирует врача по номеру телефона и паролю",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DoctorLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/doctors/{doc_id}": {
            "get": {
                "description": "Возвращает данные врача по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "Получить врача по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID врача",
                        "name": "doc_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные врача",
                        "schema": {
                            "$ref": "#/definitions/entities.Doctor"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Врач не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет информацию о враче",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Doctor"
                ],
                "summary": "Обновить данные врача",
                "parameters": [
                    {
                        "description": "Данные для обновления",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateDoctorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Обновленный врач",
                        "schema": {
                            "$ref": "#/definitions/entities.Doctor"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Врач не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            }
        },
        "/emergency/{doctor_id}": {
            "get": {
                "description": "Возвращает список экстренных приёмов, назначенных врачу на указанную дату, с пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EmergencyCall"
                ],
                "summary": "Получить экстренные приёмы врача по дате",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID врача",
                        "name": "doctor_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата в формате YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список приёмов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.EmergencyCall"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос или параметры",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            }
        },
        "/hospital/patients/{pat_id}": {
            "get": {
                "description": "Возвращает информацию о приёме",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reception"
                ],
                "summary": "Получить список приёмов пациента по его ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID приёма",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о приёме",
                        "schema": {
                            "$ref": "#/definitions/entities.ReceptionHospital"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Приём не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            }
        },
        "/hospital/{doc_id}": {
            "get": {
                "description": "Возвращает информацию о приёме",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reception"
                ],
                "summary": "Получить приём по доктору",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID доктора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о приёме",
                        "schema": {
                            "$ref": "#/definitions/entities.ReceptionHospital"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Приём не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            }
        },
        "/hospital/{recep_id}": {
            "put": {
                "description": "Обновляет информацию о приёе в больнице",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reception"
                ],
                "summary": "Обновить приём в больнице",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID приёма",
                        "name": "recep_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateReceptionHospitalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.ReceptionHospital"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/medcard/{pat_id}": {
            "get": {
                "description": "Возвращает полную информацию из медицинской карты пациента",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Medcard"
                ],
                "summary": "Получить медкарту по ID пациента",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пациента",
                        "name": "pat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Медицинская карта пациента",
                        "schema": {
                            "$ref": "#/definitions/models.MedCardResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID пациента",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Медкарта не найдена",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет информацию в медицинской карте пациента",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Medcard"
                ],
                "summary": "Обновить данные медицинской карты",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пациента",
                        "name": "pat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления медкарты",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateMedCardRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Обновленная медицинская карта",
                        "schema": {
                            "$ref": "#/definitions/models.MedCardResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Медкарта не найдена",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации данных",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            }
        },
        "/patients": {
            "get": {
                "description": "Возвращает список пациентов с возможностью пагинации и фильтрации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Получить список пациентов",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Номер страницы (по умолчанию 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Количество записей на странице (по умолчанию 0 — без ограничения)",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фильтр в формате field.operation.value. Примеры: full_name.like.Анна, birth_date.eq.1988-07-14",
                        "name": "filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список пациентов",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает нового пациента с персональными и контактными данными",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Создать нового пациента",
                "parameters": [
                    {
                        "description": "Данные пациента",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreatePatientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Созданный пациент",
                        "schema": {
                            "$ref": "#/definitions/entities.Patient"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации данных",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            }
        },
        "/patients/{pat_id}": {
            "get": {
                "description": "Возвращает полную информацию о пациенте",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Получить пациента по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пациента",
                        "name": "pat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о пациенте",
                        "schema": {
                            "$ref": "#/definitions/entities.Patient"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Пациент не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет информацию о пациенте",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Обновить данные пациента",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пациента",
                        "name": "pat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdatePatientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Обновленный пациент",
                        "schema": {
                            "$ref": "#/definitions/entities.Patient"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Пациент не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет пациента по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient"
                ],
                "summary": "Удалить пациента",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пациента",
                        "name": "pat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Пациент не найден",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            }
        },
        "/smp/{doctor_id}/receptions": {
            "get": {
                "description": "Возвращает список приёмов скорой медицинской помощи для указанного врача с пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMP"
                ],
                "summary": "Получить СМП приёмы врача по дате",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID врача",
                        "name": "doctor_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "Количество записей на страницу",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о приёме скорой помощи",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.ReceptionSMP"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    }
                }
            }
        },
        "/smp/{smp_id}": {
            "get": {
                "description": "Возвращает информацию о приёме скорой медицинской помощи вместе со списком медицинских услуг",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMP"
                ],
                "summary": "Получить приём СМП с медуслугами по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID приёма СМП",
                        "name": "smp_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о приёме и медуслугах",
                        "schema": {
                            "$ref": "#/definitions/entities.MedService"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Приём не найден",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Возвращает созданное заключение",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SMP"
                ],
                "summary": "Создать заключение на скорой",
                "responses": {
                    "200": {
                        "description": "Заключение для пациента",
                        "schema": {
                            "$ref": "#/definitions/entities.ReceptionSMP"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResultError"
                        }
                    },
                    "404": {
                        "description": "Переданные данные некорекктны",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Allergy": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "Пенициллин"
                },
                "patient": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Patient"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.ContactInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.Doctor": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "emergency_calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.EmergencyCall"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "login": {
                    "type": "string",
                    "example": "doctor_ivanov"
                },
                "receptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionHospital"
                    }
                },
                "specialization": {
                    "$ref": "#/definitions/entities.Specialization"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.EmergencyCall": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "+79991234567"
                },
                "created_at": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string",
                    "example": "+79991234567"
                },
                "priority": {
                    "type": "boolean",
                    "example": true
                },
                "receptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionSMP"
                    }
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entities.EmergencyStatus"
                        }
                    ],
                    "example": "scheduled"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.EmergencyStatus": {
            "type": "string",
            "enum": [
                "scheduled",
                "accepted",
                "on_place",
                "completed",
                "cancelled",
                "no_show"
            ],
            "x-enum-varnames": [
                "EmergencyStatusScheduled",
                "EmergencyStatusAccepted",
                "EmergencyStatusOnPlace",
                "EmergencyStatusCompleted",
                "EmergencyStatusCancelled",
                "EmergencyStatusNoShow"
            ]
        },
        "entities.MedService": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "EKG"
                },
                "price": {
                    "type": "integer",
                    "example": 100
                },
                "receptionSMP": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionSMP"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.Patient": {
            "type": "object",
            "properties": {
                "allergy": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Allergy"
                    }
                },
                "birth_date": {
                    "type": "string",
                    "example": "1980-05-15T00:00:00Z"
                },
                "contact_info": {
                    "$ref": "#/definitions/entities.ContactInfo"
                },
                "created_at": {
                    "type": "string"
                },
                "emergency_receptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionSMP"
                    }
                },
                "full_name": {
                    "type": "string",
                    "example": "Смирнов Алексей Петрович"
                },
                "id": {
                    "type": "integer"
                },
                "is_male": {
                    "type": "boolean",
                    "example": true
                },
                "on_treatment": {
                    "type": "boolean",
                    "example": false
                },
                "personal_info": {
                    "$ref": "#/definitions/entities.PersonalInfo"
                },
                "receptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ReceptionHospital"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.PersonalInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "oms": {
                    "type": "string",
                    "example": "1234567890123456"
                },
                "passport_series": {
                    "type": "string",
                    "example": "4510 123456"
                },
                "patient_id": {
                    "type": "integer",
                    "example": 1
                },
                "snils": {
                    "type": "string",
                    "example": "123-456-789 00"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.ReceptionHospital": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Москва, ул. Ленина, д. 15"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string",
                    "example": "2023-10-15T14:30:00Z"
                },
                "diagnosis": {
                    "type": "string",
                    "example": "ОРВИ"
                },
                "doctor_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer"
                },
                "patient_id": {
                    "type": "integer",
                    "example": 1
                },
                "recommendations": {
                    "type": "string",
                    "example": "Постельный режим"
                },
                "specialization_data": {
                    "description": "Специализированные данные",
                    "type": "object"
                },
                "specialization_data_decoded": {},
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entities.ReceptionStatus"
                        }
                    ],
                    "example": "scheduled"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.ReceptionSMP": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "diagnosis": {
                    "type": "string",
                    "example": "ОРВИ"
                },
                "doctor_id": {
                    "type": "integer",
                    "example": 1
                },
                "emergency_call_id": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer"
                },
                "med_services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.MedService"
                    }
                },
                "patient_id": {
                    "type": "integer",
                    "example": 1
                },
                "recommendations": {
                    "type": "string",
                    "example": "Постельный режим"
                },
                "specialization_data": {
                    "description": "Специализированные данные",
                    "type": "object"
                },
                "specialization_data_decoded": {},
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entities.ReceptionStatus": {
            "type": "string",
            "enum": [
                "scheduled",
                "completed",
                "cancelled",
                "no_show"
            ],
            "x-enum-varnames": [
                "StatusScheduled",
                "StatusCompleted",
                "StatusCancelled",
                "StatusNoShow"
            ]
        },
        "entities.Specialization": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string",
                    "example": "Терапевт"
                }
            }
        },
        "handlers.ResultError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "description": "[RULE]: must be one of codes from table (Check DEV.PAGE)",
                            "type": "integer",
                            "example": 400
                        },
                        "message": {
                            "type": "string",
                            "example": "Bad request"
                        }
                    }
                },
                "status": {
                    "description": "error",
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "handlers.ResultResponse": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "description": "[AVALIABLE]: object, array of objects, empty"
                        },
                        "message": {
                            "type": "string",
                            "example": "Success operation"
                        },
                        "type": {
                            "description": "[AVALIABLE]: object, array, empty",
                            "type": "string",
                            "example": "object"
                        }
                    }
                },
                "status": {
                    "description": "ok",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "models.AllergyResponse": {
            "description": "Ответ с названием аллергии",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Только название аллергии",
                    "type": "string",
                    "example": "Пыльца"
                }
            }
        },
        "models.ContactInfoResponse": {
            "description": "Контактная информация пациента",
            "type": "object",
            "properties": {
                "address": {
                    "description": "Физический адрес",
                    "type": "string",
                    "example": "Москва, ул. Пушкина, д. 10"
                },
                "email": {
                    "description": "Электронная почта",
                    "type": "string",
                    "example": "patient@example.com"
                },
                "phone": {
                    "description": "Номер телефона",
                    "type": "string",
                    "example": "+79991234567"
                }
            }
        },
        "models.CreatePatientRequest": {
            "description": "Данные для создания нового пациента",
            "type": "object",
            "properties": {
                "birth_date": {
                    "description": "Дата рождения",
                    "type": "string",
                    "example": "1980-05-15"
                },
                "full_name": {
                    "description": "ФИО пациента",
                    "type": "string",
                    "example": "Смирнов Алексей Петрович"
                },
                "is_male": {
                    "description": "Пол (true - мужской)",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.DoctorLoginRequest": {
            "description": "Запрос для входа врача в систему",
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "Пароль",
                    "type": "string",
                    "example": "password1"
                },
                "username": {
                    "description": "Логин (телефон)",
                    "type": "string",
                    "example": "doctor1"
                }
            }
        },
        "models.MedCardResponse": {
            "description": "Содержит всю медицинскую информацию о пациенте",
            "type": "object",
            "properties": {
                "allergy": {
                    "description": "Список аллергий",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AllergyResponse"
                    }
                },
                "contact_info": {
                    "description": "Контактные данные",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ContactInfoResponse"
                        }
                    ]
                },
                "patient": {
                    "description": "Основные данные пациента",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ShortPatientResponse"
                        }
                    ]
                },
                "personal_info": {
                    "description": "Персональная информация",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PersonalInfoResponse"
                        }
                    ]
                }
            }
        },
        "models.PersonalInfoResponse": {
            "description": "Документы и идентификационные данные пациента",
            "type": "object",
            "properties": {
                "oms": {
                    "description": "Номер полиса ОМС",
                    "type": "string",
                    "example": "1234567890123456"
                },
                "passport_series": {
                    "description": "Серия и номер паспорта",
                    "type": "string",
                    "example": "4510 123456"
                },
                "snils": {
                    "description": "Номер СНИЛС",
                    "type": "string",
                    "example": "123-456-789 00"
                }
            }
        },
        "models.ShortPatientResponse": {
            "description": "Сокращенные данные пациента",
            "type": "object",
            "properties": {
                "birth_date": {
                    "description": "Дата рождения",
                    "type": "string",
                    "example": "1980-05-15T00:00:00Z"
                },
                "full_name": {
                    "description": "ФИО пациента",
                    "type": "string",
                    "example": "Смирнов Алексей Петрович"
                },
                "id": {
                    "description": "ID пациента",
                    "type": "integer"
                },
                "is_male": {
                    "description": "Пол (true - мужской)",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.UpdateDoctorRequest": {
            "description": "Используется для изменения информации о враче",
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "Новое ФИО",
                    "type": "string",
                    "example": "Иванов Иван Иванович"
                },
                "id": {
                    "description": "ID врача для обновления",
                    "type": "integer",
                    "example": 1
                },
                "login": {
                    "description": "Новый логин",
                    "type": "string",
                    "example": "+79123456789"
                },
                "password": {
                    "description": "Новый пароль",
                    "type": "string",
                    "example": "newpassword123"
                },
                "specialization_id": {
                    "description": "Новая специализация",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.UpdateMedCardRequest": {
            "description": "Содержит всю медицинскую информацию о пациенте",
            "type": "object",
            "properties": {
                "allergy": {
                    "description": "Список аллергий",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AllergyResponse"
                    }
                },
                "contact_info": {
                    "description": "Контактные данные",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ContactInfoResponse"
                        }
                    ]
                },
                "patient": {
                    "description": "Основные данные пациента",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ShortPatientResponse"
                        }
                    ]
                },
                "personal_info": {
                    "description": "Персональная информация",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PersonalInfoResponse"
                        }
                    ]
                }
            }
        },
        "models.UpdatePatientRequest": {
            "description": "Данные для обновления информации о пациенте",
            "type": "object",
            "properties": {
                "birth_date": {
                    "description": "Дата рождения",
                    "type": "string",
                    "example": "1980-05-15"
                },
                "full_name": {
                    "description": "ФИО пациента",
                    "type": "string",
                    "example": "Смирнов Алексей Петрович"
                },
                "id": {
                    "description": "ID пациента",
                    "type": "integer",
                    "example": 10
                },
                "is_male": {
                    "description": "Пол (true - мужской)",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.UpdateReceptionHospitalRequest": {
            "type": "object",
            "properties": {
                "diagnosis": {
                    "type": "string",
                    "example": "Грипп"
                },
                "id": {
                    "type": "integer"
                },
                "recommendations": {
                    "type": "string",
                    "example": "Постельный режим"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/entities.ReceptionStatus"
                        }
                    ],
                    "example": "scheduled"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ClinicHub API",
	Description:      "API для работы с приёмами пациентов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
